### ISSUE TITLE
Allow extra options like sharpen, blur, pixelate, etc.

### ISSUE THREAD

**Issue by SmaugPool** [klen/imgproxy#1]
Thanks for the library, it is nice to use.

It would be really useful to be able to add extra options like sharpen, blur, pixelate, etc.

https://docs.imgproxy.net/generating_the_url

As new options could be added, maybe having the option to add custom ones could avoid limitations in the future.

Thank you

**Comment by klen** [comment]
@SmaugPool Maybe there is a lack of documentation but the library supports any options.

```python
    from imgproxy import ImgProxy

    img_url = ImgProxy('https://picsum.photos/1000', proxy_host='https://imgproxy.com')

    # Get rotated and blured image
    blured_rotated = img_url('blur:0.5', 'rotate:30')
```

I've added more about this into the README.

**Comment by SmaugPool** [comment]
Great! Sorry to have missed that and thank you for the README update.
